---
id: ai-studio-commit-convention
trigger: "when writing a commit message"
confidence: 0.9
domain: git
source: local-repo-analysis
---

# Use Chinese Conventional Commits

## Action
Prefix commits with: feat:, fix:, refactor:, docs:, chore:, test:

Follow the format: `<type>(<scope>): <description in Chinese>`

## Evidence
- Analyzed 100 commits
- 95%+ follow conventional commit format
- Most commits include Chinese descriptions

## Examples
```
feat: 添加 Milky 模块封装 OneBot API 客户端
fix: 修复消息处理多个问题
refactor: 重构 AI 模块包路径 com.shuanglin.bot → com.shuanglin.ai
docs: 更新 CLAUDE.md 添加权限系统文档
chore: 更新 IDE 配置和 ChatStart
test: 添加权限系统测试类
```